// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppName() {
  return window['go']['main']['App']['AppName']();
}

export function ApplySCTheme(arg1) {
  return window['go']['main']['App']['ApplySCTheme'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSongs() {
  return window['go']['main']['App']['GetSongs']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenCommentInBrowser(arg1, arg2) {
  return window['go']['main']['App']['OpenCommentInBrowser'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SubmitVote(arg1, arg2) {
  return window['go']['main']['App']['SubmitVote'](arg1, arg2);
}

export function UpdateAutoScroll(arg1) {
  return window['go']['main']['App']['UpdateAutoScroll'](arg1);
}

export function UpdateTheme(arg1) {
  return window['go']['main']['App']['UpdateTheme'](arg1);
}
