// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function GetSongs():Promise<main.AppState>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function OpenCommentInBrowser(arg1:string,arg2:number):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SubmitVote(arg1:string,arg2:number):Promise<void>;

export function UpdateAutoScroll(arg1:boolean):Promise<void>;

export function UpdateTheme(arg1:string):Promise<void>;
